# Performance Analysis Pack
# Responsibility: Core domain managing Analysis model, InitiatePerformanceAnalysis command, and analysis orchestration.

# Change to `true` to turn on dependency checks for this package
enforce_dependencies: true

# A list of this package's dependencies
# This pack depends on trades for trade data and data_fetching for historical market data
dependencies:
- "packs/trades"
- "packs/data_fetching"

# Metadata
metadata:
  description: "Core analysis engine that orchestrates performance calculations"
  owner: "Analytics Team"