# Trading Strategies Pack
# Responsibility: Manages the Algorithm model and related business logic.

# Change to `true` to turn on dependency checks for this package
enforce_dependencies: true

# A list of this package's dependencies
# This pack depends on the root package for ApplicationRecord, data_fetching for QuiverTrade, and trades for AlpacaService
# NOTE: This creates a circular dependency with trades package, but is required by the tech spec
dependencies:
  - "."
  - "packs/data_fetching"
  - "packs/trades"

# Metadata
metadata:
  description: "Manages trading algorithms and strategy definitions"
  owner: "Trading Team"