# Trading Strategies Pack
# Responsibility: Manages the Algorithm model and related business logic.

# Change to `true` to turn on dependency checks for this package
enforce_dependencies: true

# A list of this package's dependencies
# This pack has no dependencies as it's a foundational pack
dependencies: []

# Metadata
metadata:
  description: "Manages trading algorithms and strategy definitions"
  owner: "Trading Team"