# Data Fetching Pack
# Responsibility: Manages the HistoricalBar cache model and all interactions with external Alpaca Market Data API.

# Change to `true` to turn on dependency checks for this package
enforce_dependencies: true

# A list of this package's dependencies
# Depends on root package for ApplicationRecord
dependencies: ["."]

# Metadata
metadata:
  description: "Handles external market data fetching and caching from Alpaca API"
  owner: "Data Team"